name: Deploy to GitHub Pages

on:
  push:
    branches:
      - source

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: Cache node_modules of Suka theme
        uses: actions/cache@v2
        with:
          path: themes/suka/node_modules
          key: ${{ runner.OS }}-npm-cache-themes-suka
          restore-keys: |
            ${{ runner.OS }}-npm-cache-themes-suka

      - name: Install dependencies
        run: yarn

      - name: Install dependencies for Suka theme
        working-directory: ./themes/suka
        run: yarn

      - name: Build
        run: yarn build

      - name: Bypass warnings about Jekyll themes
        run: touch ./public/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
